weight = abs(float (input("Please enter your weight in kilogram : ")))
height = abs(float (input("Please enter your height in meter : ")))
BMI = weight /(height **2)
if BMI< 18.5 : print("Underweight")
elif BMI < 25 : print("Normal")
elif BMI < 30 : print("Overweight")
elif BMI < 35 : print("Obese")
else : print("Extremly-Obese")